### ISSUE TITLE
improve pretty printing

### ISSUE THREAD

**Issue by goolord** [goolord/jsedsl#11]
pretty printing anything with an indentation level does not produce a very pretty result

**Comment by chessai** [comment]
can we track what scope we are in? we want things to be indented based on scope (at least almost always)

**Comment by goolord** [comment]
we don't need to, as long as we indent everything inside braces it will have the correct indentation level

**Comment by goolord** [comment]
```javascript
function foo() {
  console.log('bar');
  const baz = function(x) {
    return x + 1;
  }
  return baz(2)
}
```
see, this is valid. the indentation is based on the scope just by indenting on braces

**Comment by chessai** [comment]
ok, that's fine. was that generated by us?

**Comment by goolord** [comment]
no

**Comment by chessai** [comment]
you're a mean one, mr. grinch. you reallllly are a heel

**Comment by chessai** [comment]
Ok, my question then reduces to: can we tell if we are in braces, and how deeply nested in braces we are?

**Comment by goolord** [comment]
no

**Comment by goolord** [comment]
well, we could if we wanted to track that additionally with the identifier number, but I don't think it's necessary

**Comment by chessai** [comment]
Okay, then how are we going to indent with braces as you suggest? How in the code do we/can we know how far to indent?

**Comment by goolord** [comment]
I'm using https://hackage.haskell.org/package/pretty for pretty printing, which can take care of this afaik. right now things are actually being indented already https://github.com/goolord/jsedsl/blob/master/src/Reboot.hs#L292 , but the `$+$` function isn't really the right choice here. the indentation we get here is like
```
foo {body
     next
     next
}
```

**Comment by chessai** [comment]
Ah ok

**Comment by goolord** [comment]
should be done
