### ISSUE TITLE
how to express functions?

### ISSUE THREAD

**Issue by chessai** [goolord/jsedsl#2]
Are we going to allow higher-order functions? In that case, function needs to be a part of 'Value'. If we aren't, then they should probably be put into 'Action'. @andrewthad, thoughts?

**Comment by andrewthad** [comment]
Let's disallow user-defined higher-order functions for the time being. We can have primitives for `map` and `fold`. If more complicated needs arise, we can rethink this.

**Comment by chessai** [comment]
Do you mean to say that we should not allow users to construct functions, but instead that they must pass functions in to HOFs defined by us?

**Comment by andrewthad** [comment]
Precisely. The users get to write the functions they pass as arguments to HOFs like `map`, `fold`, etc., but they are not able to implement `map` and `fold` themselves.
