### ISSUE TITLE
are we actually going to use the key monad?

### ISSUE THREAD

**Issue by chessai** [goolord/jsedsl#6]
The efficient version of the Key Monad as defined in the paper [The Key Monad: Type-Safe Unconstrained Dynamic Typing](https://people.seas.harvard.edu/~pbuiras/publications/KeyMonadHaskell2016.pdf) is in src/Key.hs.

however, i'm not sure how this integrates into the current sketch of things. It seems like `Key` is a less information-dense version of `Binding`, in that `Binding` contains `Strategy`/`Universe` information.

**Comment by andrewthad** [comment]
We should not actually use `Key` as described in the paper. It's a source of inspiration, but our needs are subtly different.
